---
apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    app: hello   
spec:
  containers:
  - name: hello
    image: docker push sindhans/demo:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello      
spec:
  type: NodePort
  selector:
    app: hello
  ports:
  - port: 80
    nodePort: 30001
